### ISSUE TITLE
Detect improper self-qualified names

### ISSUE THREAD

**Issue by fredrikekre** [ericphanson/ExplicitImports.jl#55]
Sometimes you see "self-qualified" names like e.g.
```julia
module A

f() = #...

g() = A.f()

end
```
This usually comes from prototyping code outside the module and then forgetting to remove the `A.` when putting it inside.

It would be great to have a check for this! It might be a little out of scope but I think this could be qualified as a "improper qualification" which already is included here. In any case I would assume the code to detect this is basically already there. Thoughts?

**Comment by ericphanson** [comment]
Hm, yeah, I agree this could make sense as an "improper" qualified access. I think it would have to be a new `check_` function, since it seems out of scope for `check_all_qualified_accesses_via_owners` (and I don't want non-breaking releases of ExplicitExports to start failing folks' tests or CI runs), but that's alright.

It would indeed to be easy to add, since we have access to both the qualifying module and the module the name is in, so we can just check if they are `==` (namely, `current_mod` and `mod` in [here](https://github.com/ericphanson/ExplicitImports.jl/blob/ba63bec7583e89a0bb9271c9051962396ad27ec8/src/qualified_names.jl#L38))

**Comment by fredrikekre** [comment]
Thanks!
