### ISSUE TITLE
Feature request: compatibility with `Compat.jl`

### ISSUE THREAD

**Issue by MilesCranmer** [ericphanson/ExplicitImports.jl#70]
Just flagging in case it's something to consider. I use Compat a lot for new Julia features on old versions. This gives me some errors like:

```
Additionally, module DynamicExpressions.NodeUtilsModule explicitly imports 1 name from non-owner modules:
- `Returns` has owner Base but it was imported from Compat at /Users/mcranmer/PermaDocuments/SymbolicRegressionMonorepo/DynamicExpressions.jl/src/NodeUtils.jl:3:15
```

Not sure if you want to skip Compat or not?

**Comment by ericphanson** [comment]
hm, good point. We do allow the `skip` kwarg in `check_all_explicit_imports_via_owners` and so forth, but don't expose it at the printing level. So that would be one path to make it configurable.

We could also just always skip it, I think that would be pretty reasonable. Trying to think about semver - it would not cause errors to emit fewer issues, so I think I'd be OK with it as non-breaking...
