### ISSUE TITLE
one branch in `ExplicitImports.main` is untested

### ISSUE THREAD

**Issue by ericphanson** [ericphanson/ExplicitImports.jl#90]
https://github.com/ericphanson/ExplicitImports.jl/pull/89

**Comment by abelsiqueira** [comment]
I might help, but I'm not sure how to best approach this.
Since `main` expects to find a `Project.toml`, I see the following alternatives:

1. Use `ExplicitImports.jl` itself for testing. Maybe not sustainable in the long term.
2. Use `test/TestPkg`. It passes the checks, though. So we can't check failure.
3. Create - maybe programatically - one or more packages inside `test/` that fails some tests.

I would try a combination of 2 and 3:

- Test that `all` passes for 2.
- Create a new package in Test.
- Test that `all` fails for 3.
- Test that `exclude_...` passes for 3.
- Test that inclusion without `all` passes for 3.

What do you think?

**Comment by ericphanson** [comment]
IIUC, if we tested `test/TestPkg` that would have caught the bug that we fixed in #89. So I think that would be good enough; the checks themselves are tested elsewhere, including failure cases. It would be nice to also be able to test we aren't printing the stacktraces though which would need a failing test. But for this issue I think your option (2) is enough, and relatively simple.

**Comment by abelsiqueira** [comment]
I created #91 with the basic tests you suggested. I'm not sure how to test the stacktraces.
To get close to 100% coverage, we are missing tests on the error messages.
